tasks:
  - init: |
      sudo apt install cmake
      chmod +x build.sh
  - command:
      "./build.sh" 

github:
  prebuilds:
    master: true
    branches: false
    addComments: true
    addCheck: true
