tasks:
  - before:
      "sudo apt install cmake"
  - init:
      "chmod +x build.sh"
  - command:
      "./build.sh" 

github:
  prebuilds:
    master: true
    branches: false
    addComments: true
    addCheck: true
