tasks:
  - init: |
      sudo apt install cmake --assume-yes
      chmod +x build.sh

github:
  prebuilds:
    master: true
    branches: false
    addComments: true
    addCheck: true

vscode:
  extensions:
    - notskm.clang-tidy
    - twxs.cmake
